import fs from 'node:fs'
const links = {
  site: 'https://oceanid.io/',
  account: "http://localhost:8080/account.html",
  logo: 'https://storage.googleapis.com/oceanid-public/logo.png',
  logoText: 'https://storage.googleapis.com/oceanid-public/logo-text.png',
  indiegogo: 'https://www.indiegogo.com/projects/oceanid/oceanid-one-app-for-life-at-sea',
  facebookPage: 'https://www.facebook.com/OceanidSeaLife',
  facebookGroup: 'https://www.facebook.com/groups/oceanid',
  instagram: 'https://www.instagram.com/oceanidsealife/',
  discord: 'https://discord.gg/caUTTgQFMa',
  youtube: 'https://www.youtube.com/@oceanid-sea-life',
}
const REWARDS = {
  OPER_PRO_3M: { marketingName: "Captain's Reward", shortHeadline: '2 months of Oceanid PRO, free', body: 'Unlimited vessels and unlimited paid trips on the PRO plan, free for 2 months (€60 value).', icon: '★' },
}
const escapeHtml = (v) => v.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')
const emailHeader = () => `<tr><td style="padding:22px 26px;background:#ffffff;border-bottom:1px solid #e5edf6;"><a href="${links.site}" style="display:inline-flex;align-items:center;text-decoration:none;"><img src="${links.logo}" width="34" height="34" alt="Oceanid" style="display:inline-block;vertical-align:middle;border:0;margin-right:10px;"><img src="${links.logoText}" height="22" alt="Oceanid" style="display:inline-block;vertical-align:middle;border:0;max-width:150px;"></a></td></tr>`
const ctaButton = (href, label) => `<a href="${href}" style="display:inline-block;background:#5c6bc0;color:#ffffff;text-decoration:none;font-size:16px;font-weight:800;line-height:1;padding:16px 28px;border-radius:14px;box-shadow:0 10px 22px rgba(92,107,192,.28);">${label}</a>`
const communityBlock = () => {
  const ch = (h,l) => `<a href="${h}" style="display:block;text-align:center;background:#ffffff;color:#3949ab;text-decoration:none;font-size:14px;font-weight:800;padding:13px 16px;border:1px solid #d8e0f0;border-radius:10px;margin:0 0 10px;">${l}</a>`
  return `<tr><td style="padding:8px 32px 8px;background:#ffffff;"><p style="margin:0 0 12px;color:#39445a;font-size:14px;line-height:1.7;">Oceanid is building one app for life at sea: discover trips, connect with crews, find marina services, and join a community built around real sea life.</p><p style="margin:0;color:#39445a;font-size:14px;line-height:1.7;">The most helpful next step is to support the launch and join the community channels where we share updates first.</p></td></tr><tr><td align="center" style="padding:18px 32px 6px;background:#ffffff;">${ctaButton(links.indiegogo,'Back Oceanid on Indiegogo')}</td></tr><tr><td style="padding:18px 32px 8px;background:#ffffff;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:20px;background:#f5f8fc;border:1px solid #dce6f2;border-radius:14px;"><p style="margin:0 0 4px;color:#162033;font-size:16px;font-weight:800;">Join the crew</p><p style="margin:0 0 14px;color:#5b667a;font-size:14px;line-height:1.6;">Meet early members, follow build updates, and help shape Oceanid before launch.</p>${ch(links.facebookGroup,'Join the Facebook group')}${ch(links.discord,'Join Discord')}${ch(links.instagram,'Follow on Instagram')}${ch(links.youtube,'Watch on YouTube')}${ch(links.facebookPage,'Follow the Facebook page')}</td></tr></table></td></tr>`
}
const emailFooter = () => `<tr><td style="padding:8px 32px 28px;background:#ffffff;"><p style="margin:0;color:#5b667a;font-size:14px;line-height:1.7;">See you on the water.</p><p style="margin:14px 0 0;color:#162033;font-size:14px;line-height:1.6;font-weight:800;">The Oceanid Team</p><p style="margin:2px 0 0;color:#6c7588;font-size:13px;line-height:1.6;"><a href="mailto:contact@oceanid.io" style="color:#3949ab;text-decoration:none;">contact@oceanid.io</a></p></td></tr><tr><td style="padding:18px 32px;background:#f5f8fc;border-top:1px solid #e5edf6;"><p style="margin:0;color:#6c7588;font-size:12px;line-height:1.6;">You received this email because you registered for Oceanid early access at <a href="${links.site}" style="color:#3949ab;text-decoration:none;">oceanid.io</a>.</p></td></tr>`
const emailShell = (pre, inner) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Oceanid</title></head><body style="margin:0;padding:0;background:#eef4fb;color:#162033;font-family:Manrope,Inter,Segoe UI,Arial,sans-serif;"><div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">${pre}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#eef4fb;margin:0;padding:28px 12px;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border:1px solid #dce6f2;border-radius:18px;overflow:hidden;box-shadow:0 18px 48px rgba(22,32,51,.12);">${emailHeader()}${inner}${communityBlock()}${emailFooter()}</table></td></tr></table></body></html>`

function buildWelcome(name, rewardCode, claimToken) {
  const r = REWARDS[rewardCode]
  const url = links.account
  const sn = escapeHtml(name), sr = escapeHtml(r.marketingName)
  const inner = `<tr><td style="padding:38px 32px 18px;background:#ffffff;"><p style="margin:0 0 10px;color:#5c6bc0;font-size:13px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;">Your reward is reserved</p><h1 style="margin:0 0 16px;color:#162033;font-size:32px;line-height:1.16;font-weight:800;letter-spacing:0;">Welcome aboard, ${sn}.</h1><p style="margin:0;color:#39445a;font-size:16px;line-height:1.6;">Thank you for joining Oceanid early. You picked <strong>${sr}</strong>, and we've locked it in for you.</p></td></tr><tr><td style="padding:8px 32px 4px;background:#ffffff;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:18px 20px;background:#f5f8fc;border:1px solid #dce6f2;border-radius:14px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td width="44" valign="top" style="padding-right:14px;"><div style="width:40px;height:40px;border-radius:12px;background:#eef0fb;color:#3949ab;font-size:20px;font-weight:800;text-align:center;line-height:40px;">${r.icon}</div></td><td><p style="margin:0 0 4px;color:#5c6bc0;font-size:11px;font-weight:800;letter-spacing:.16em;text-transform:uppercase;">Your reward</p><p style="margin:0 0 4px;color:#162033;font-size:17px;font-weight:800;line-height:1.3;">${escapeHtml(r.shortHeadline)}</p><p style="margin:0;color:#5b667a;font-size:13px;line-height:1.6;">${escapeHtml(r.body)}</p></td></tr></table></td></tr></table></td></tr><tr><td style="padding:22px 32px 4px;background:#ffffff;"><p style="margin:0 0 10px;color:#162033;font-size:16px;font-weight:800;">View your reward in the app</p><p style="margin:0 0 6px;color:#39445a;font-size:14px;line-height:1.7;">1. Tap the button below to open your Oceanid account.</p><p style="margin:0 0 6px;color:#39445a;font-size:14px;line-height:1.7;">2. Continue with Google, or your email and a password.</p><p style="margin:0;color:#39445a;font-size:14px;line-height:1.7;">3. Open the <strong>Rewards</strong> tab to view your reward or switch to a different one anytime.</p></td></tr><tr><td align="center" style="padding:22px 32px 12px;background:#ffffff;">${ctaButton(url,'Open your Oceanid account')}<p style="margin:14px 0 0;color:#6c7588;font-size:12px;line-height:1.5;"></p></td></tr>`
  return emailShell(`You picked ${sr}. Sign in to oceanid.io/account to activate it.`, inner)
}

function buildLegacy(name, role, claimToken) {
  const url = links.account
  const sn = escapeHtml(name)
  const roleCopy = role ? ` as <strong>${escapeHtml(role)}</strong>` : ''
  const card = (icon,t,b) => `<tr><td style="padding:14px 16px;background:#ffffff;border:1px solid #dce6f2;border-radius:12px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td width="40" valign="top" style="padding-right:12px;"><div style="width:36px;height:36px;border-radius:10px;background:#eef0fb;color:#3949ab;font-size:18px;font-weight:800;text-align:center;line-height:36px;">${icon}</div></td><td><p style="margin:0 0 4px;color:#162033;font-size:15px;font-weight:800;line-height:1.3;">${t}</p><p style="margin:0;color:#5b667a;font-size:13px;line-height:1.55;">${b}</p></td></tr></table></td></tr><tr><td style="height:10px;line-height:10px;font-size:0;">&nbsp;</td></tr>`
  const inner = `<tr><td style="padding:38px 32px 18px;background:#ffffff;"><p style="margin:0 0 10px;color:#5c6bc0;font-size:13px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;">Your free reward is reserved</p><h1 style="margin:0 0 16px;color:#162033;font-size:32px;line-height:1.16;font-weight:800;letter-spacing:0;">Welcome aboard, ${sn}.</h1><p style="margin:0;color:#39445a;font-size:16px;line-height:1.6;">Thank you for registering${roleCopy}. As an early member, you get to pick one of these rewards. Free for 2 months.</p></td></tr><tr><td style="padding:8px 32px 4px;background:#ffffff;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0">${card('★','2 months of Oceanid PRO, free','For captains and fleet managers. Unlimited vessels and unlimited paid trips on the PRO plan, free for 2 months (€60 value).')}${card('%','Tailored partner offers','B2B partner perks. Our team will reach out to set up commercial terms that fit your business.')}${card('⛵','No booking fees for 2 months','For travelers. The 5% Oceanid booking fee is waived on every trip you book in your first 2 months.')}</table></td></tr><tr><td style="padding:18px 32px 4px;background:#ffffff;"><p style="margin:0 0 8px;color:#162033;font-size:16px;font-weight:800;">How to pick your reward</p><p style="margin:0 0 6px;color:#39445a;font-size:14px;line-height:1.7;">1. Tap the button below to open your Oceanid account.</p><p style="margin:0 0 6px;color:#39445a;font-size:14px;line-height:1.7;">2. Continue with Google, or your email and a password.</p><p style="margin:0;color:#39445a;font-size:14px;line-height:1.7;">3. Open the <strong>Rewards</strong> tab to pick your reward or switch later.</p></td></tr><tr><td align="center" style="padding:22px 32px 12px;background:#ffffff;">${ctaButton(url,'Open your Oceanid account')}<p style="margin:14px 0 0;color:#6c7588;font-size:12px;line-height:1.5;"></p></td></tr>`
  return emailShell('Your free reward is reserved. Sign in to oceanid.io/account to pick it.', inner)
}

const FAKE_TOKEN = '11111111-2222-3333-4444-555555555555'
fs.writeFileSync('/Users/ika/Dev/Oceanid/landing/.email-preview/A-reward-picked.html', buildWelcome('Ika', 'OPER_PRO_3M', FAKE_TOKEN))
fs.writeFileSync('/Users/ika/Dev/Oceanid/landing/.email-preview/B-no-reward.html', buildLegacy("Ika", "", FAKE_TOKEN))
console.log('Wrote A-reward-picked.html and B-no-reward.html')
